allianceauth/authentication/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView

from . import views

app_name = 'authentication'

urlpatterns = [
    url(r'^$', login_required(TemplateView.as_view(template_name='authentication/dashboard.html')),),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='login'),
    url(r'^account/characters/main/$', views.main_character_change, name='change_main_character'),
    url(r'^account/characters/add/$', views.add_character, name='add_character'),
    url(r'^help/$', login_required(TemplateView.as_view(template_name='allianceauth/help.html')), name='help'),
    url(r'^dashboard/$',
        login_required(TemplateView.as_view(template_name='authentication/dashboard.html')), name='dashboard'),
]

allianceauth/fleetup/urls.py
from django.conf.urls import url

from . import views

app_name = 'fleetup'

urlpatterns = [
    url(r'^$', views.fleetup_view, name='view'),
    url(r'^fittings/$', views.fleetup_fittings, name='fittings'),
    url(r'^fittings/(?P<fittingnumber>[0-9]+)/$', views.fleetup_fitting, name='fitting'),
    url(r'^doctrines/$', views.fleetup_doctrines, name='doctrines'),
    url(r'^characters/$', views.fleetup_characters, name='characters'),
    url(r'^doctrines/(?P<doctrinenumber>[0-9]+)/$', views.fleetup_doctrine, name='doctrine'),
]

allianceauth/notifications/urls.py
from django.conf.urls import url
from . import views

app_name = 'notifications'
# Notifications
urlpatterns = [
    url(r'^remove_notifications/(\w+)/$', views.remove_notification, name='remove'),
    url(r'^notifications/mark_all_read/$', views.mark_all_read, name='mark_all_read'),
    url(r'^notifications/delete_all_read/$', views.delete_all_read, name='delete_all_read'),
    url(r'^notifications/$', views.notification_list, name='list'),
    url(r'^notifications/(\w+)/$', views.notification_view, name='view'),
]

allianceauth/optimer/urls.py
from django.conf.urls import url

from . import views

app_name = 'optimer'

urlpatterns = [
    url(r'^$', views.optimer_view, name='view'),
    url(r'^add$', views.add_optimer_view, name='add'),
    url(r'^(\w+)/remove$', views.remove_optimer, name='remove'),
    url(r'^(\w+)/edit$', views.edit_optimer, name='edit'),
    ]

allianceauth/srp/urls.py
from django.conf.urls import url

from . import views

app_name = 'srp'

urlpatterns = [
    # SRP URLS
    url(r'^$', views.srp_management, name='management'),
    url(r'^all/$', views.srp_management, {'all': True}, name='all'),
    url(r'^(\w+)/view$', views.srp_fleet_view, name='fleet'),
    url(r'^add/$', views.srp_fleet_add_view, name='add'),
    url(r'^(\w+)/edit$', views.srp_fleet_edit_view, name='edit'),
    url(r'^(\w+)/request', views.srp_request_view, name='request'),

    # SRP URLS
    url(r'^(\w+)/remove$', views.srp_fleet_remove, name='remove'),
    url(r'^(\w+)/disable$', views.srp_fleet_disable, name='disable'),
    url(r'^(\w+)/enable$', views.srp_fleet_enable, name='enable'),
    url(r'^(\w+)/complete$', views.srp_fleet_mark_completed,
        name='mark_completed'),
    url(r'^(\w+)/incomplete$', views.srp_fleet_mark_uncompleted,
        name='mark_uncompleted'),
    url(r'^request/remove/', views.srp_request_remove,
        name="request_remove"),
    url(r'^request/approve/', views.srp_request_approve,
        name='request_approve'),
    url(r'^request/reject/', views.srp_request_reject,
        name='request_reject'),
    url(r'^request/(\w+)/update', views.srp_request_update_amount,
        name="request_update_amount"),
]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/authentication/models.py
import logging

from django.contrib.auth.models import User, Permission
from django.db import models, transaction
from django.utils.translation import ugettext_lazy as _
from allianceauth.eveonline.models import EveCharacter, EveCorporationInfo, EveAllianceInfo
from allianceauth.notifications import notify

from .managers import CharacterOwnershipManager, StateManager

logger = logging.getLogger(__name__)


class State(models.Model):
    name = models.CharField(max_length=20, unique=True)
    permissions = models.ManyToManyField(Permission, blank=True)
    priority = models.IntegerField(unique=True,
                                   help_text="Users get assigned the state with the highest priority available to them.")

    member_characters = models.ManyToManyField(EveCharacter, blank=True,
                                               help_text="Characters to which this state is available.")
    member_corporations = models.ManyToManyField(EveCorporationInfo, blank=True,
                                                 help_text="Corporations to whose members this state is available.")
    member_alliances = models.ManyToManyField(EveAllianceInfo, blank=True,
                                              help_text="Alliances to whose members this state is available.")
    public = models.BooleanField(default=False, help_text="Make this state available to any character.")

    objects = StateManager()

    class Meta:
        ordering = ['-priority']

    def __str__(self):
        return self.name

    def available_to_character(self, character):
        return self in State.objects.available_to_character(character)

    def available_to_user(self, user):
        return self in State.objects.available_to_user(user)

    def delete(self, **kwargs):
        with transaction.atomic():
            for profile in self.userprofile_set.all():
                profile.assign_state(state=State.objects.exclude(pk=self.pk).get_for_user(profile.user))
        super(State, self).delete(**kwargs)


def get_guest_state():
    try:
        return State.objects.get(name='Guest')
    except State.DoesNotExist:
        return State.objects.create(name='Guest', priority=0, public=True)


def get_guest_state_pk():
    return get_guest_state().pk


class UserProfile(models.Model):
    class Meta:
        default_permissions = ('change',)

    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE)
    main_character = models.OneToOneField(EveCharacter, blank=True, null=True, on_delete=models.SET_NULL)
    state = models.ForeignKey(State, on_delete=models.SET_DEFAULT, default=get_guest_state_pk)

    def assign_state(self, state=None, commit=True):
        if not state:
            state = State.objects.get_for_user(self.user)
        if self.state != state:
            self.state = state
            if commit:
                logger.info('Updating {} state to {}'.format(self.user, self.state))
                self.save(update_fields=['state'])
                notify(self.user, _('State Changed'),
                       _('Your user state has been changed to %(state)s') % ({'state': state}),
                       'info')
                from allianceauth.authentication.signals import state_changed
                state_changed.send(sender=self.__class__, user=self.user, state=self.state)

    def __str__(self):
        return str(self.user)


class CharacterOwnership(models.Model):
    class Meta:
        default_permissions = ('change', 'delete')
        ordering = ['user', 'character__character_name']

    character = models.OneToOneField(EveCharacter, on_delete=models.CASCADE, related_name='character_ownership')
    owner_hash = models.CharField(max_length=28, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='character_ownerships')

    objects = CharacterOwnershipManager()

    def __str__(self):
        return "%s: %s" % (self.user, self.character)


class OwnershipRecord(models.Model):
    character = models.ForeignKey(EveCharacter, on_delete=models.CASCADE, related_name='ownership_records')
    owner_hash = models.CharField(max_length=28, db_index=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ownership_records')
    created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return "%s: %s on %s" % (self.user, self.character, self.created)

allianceauth/corputils/models.py
import logging
import os

from allianceauth.authentication.models import CharacterOwnership, UserProfile
from bravado.exception import HTTPForbidden
from django.db import models
from esi.errors import TokenError
from esi.models import Token
from allianceauth.eveonline.models import EveCorporationInfo, EveCharacter
from allianceauth.notifications import notify

from allianceauth.corputils.managers import CorpStatsManager

SWAGGER_SPEC_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'swagger.json')
"""
Swagger spec operations:

get_characters_character_id
get_corporations_corporation_id_members
get_characters_names
"""


logger = logging.getLogger(__name__)


class CorpStats(models.Model):
    token = models.ForeignKey(Token, on_delete=models.CASCADE)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)
    last_update = models.DateTimeField(auto_now=True)

    class Meta:
        permissions = (
            ('view_corp_corpstats', 'Can view corp stats of their corporation.'),
            ('view_alliance_corpstats', 'Can view corp stats of members of their alliance.'),
            ('view_state_corpstats', 'Can view corp stats of members of their auth state.'),
        )
        verbose_name = "corp stats"
        verbose_name_plural = "corp stats"

    objects = CorpStatsManager()

    def __str__(self):
        return "%s for %s" % (self.__class__.__name__, self.corp)

    def update(self):
        try:
            c = self.token.get_esi_client(spec_file=SWAGGER_SPEC_PATH)
            assert c.Character.get_characters_character_id(character_id=self.token.character_id).result()[
                       'corporation_id'] == int(self.corp.corporation_id)
            member_ids = c.Corporation.get_corporations_corporation_id_members(
                corporation_id=self.corp.corporation_id).result()

            # requesting too many ids per call results in a HTTP400
            # the swagger spec doesn't have a maxItems count
            # manual testing says we can do over 350, but let's not risk it
            member_id_chunks = [member_ids[i:i + 255] for i in range(0, len(member_ids), 255)]
            member_name_chunks = [c.Character.get_characters_names(character_ids=id_chunk).result() for id_chunk in
                                  member_id_chunks]
            member_list = {}
            for name_chunk in member_name_chunks:
                member_list.update({m['character_id']: m['character_name'] for m in name_chunk})

            # bulk create new member models
            missing_members = [m_id for m_id in member_ids if
                               not CorpMember.objects.filter(corpstats=self, character_id=m_id).exists()]
            CorpMember.objects.bulk_create(
                [CorpMember(character_id=m_id, character_name=member_list[m_id], corpstats=self) for m_id in
                 missing_members])

            # purge old members
            self.members.exclude(character_id__in=member_ids).delete()

            # update the timer
            self.save()

        except TokenError as e:
            logger.warning("%s failed to update: %s" % (self, e))
            if self.token.user:
                notify(self.token.user, "%s failed to update with your ESI token." % self,
                       message="Your token has expired or is no longer valid. Please add a new one to create a new CorpStats.",
                       level="error")
            self.delete()
        except HTTPForbidden as e:
            logger.warning("%s failed to update: %s" % (self, e))
            if self.token.user:
                notify(self.token.user, "%s failed to update with your ESI token." % self,
                       message="%s: %s" % (e.status_code, e.message), level="error")
            self.delete()
        except AssertionError:
            logger.warning("%s token character no longer in corp." % self)
            if self.token.user:
                notify(self.token.user, "%s cannot update with your ESI token." % self,
                       message="%s cannot update with your ESI token as you have left corp." % self, level="error")
            self.delete()

    @property
    def member_count(self):
        return self.members.count()

    @property
    def user_count(self):
        return len(set([m.main_character for m in self.members.all() if m.main_character]))

    @property
    def registered_member_count(self):
        return len(self.registered_members)

    @property
    def registered_members(self):
        return self.members.filter(pk__in=[m.pk for m in self.members.all() if m.registered])

    @property
    def unregistered_member_count(self):
        return self.member_count - self.registered_member_count

    @property
    def unregistered_members(self):
        return self.members.filter(pk__in=[m.pk for m in self.members.all() if not m.registered])

    @property
    def main_count(self):
        return len(self.mains)

    @property
    def mains(self):
        return self.members.filter(pk__in=[m.pk for m in self.members.all() if
                                           m.main_character and int(m.main_character.character_id) == int(
                                               m.character_id)])

    def visible_to(self, user):
        return CorpStats.objects.filter(pk=self.pk).visible_to(user).exists()

    def can_update(self, user):
        return self.token.user == user or self.visible_to(user)

    def corp_logo(self, size=128):
        return "https://image.eveonline.com/Corporation/%s_%s.png" % (self.corp.corporation_id, size)

    def alliance_logo(self, size=128):
        if self.corp.alliance:
            return "https://image.eveonline.com/Alliance/%s_%s.png" % (self.corp.alliance.alliance_id, size)
        else:
            return "https://image.eveonline.com/Alliance/1_%s.png" % size


class CorpMember(models.Model):
    character_id = models.PositiveIntegerField()
    character_name = models.CharField(max_length=37)
    corpstats = models.ForeignKey(CorpStats, on_delete=models.CASCADE, related_name='members')

    class Meta:
        # not making character_id unique in case a character moves between two corps while only one updates
        unique_together = ('corpstats', 'character_id')
        ordering = ['character_name']

    def __str__(self):
        return self.character_name

    @property
    def character(self):
        try:
            return EveCharacter.objects.get(character_id=self.character_id)
        except EveCharacter.DoesNotExist:
            return None

    @property
    def main_character(self):
        try:
            return self.character.character_ownership.user.profile.main_character
        except (CharacterOwnership.DoesNotExist, UserProfile.DoesNotExist, AttributeError):
            return None

    @property
    def alts(self):
        if self.main_character:
            return [co.character for co in self.main_character.character_ownership.user.character_ownerships.all()]
        else:
            return []

    @property
    def registered(self):
        return CharacterOwnership.objects.filter(character__character_id=self.character_id).exists()

    def portrait_url(self, size=32):
        return "https://image.eveonline.com/Character/%s_%s.jpg" % (self.character_id, size)

    def __getattr__(self, item):
        if item.startswith('portrait_url_'):
            size = item.strip('portrait_url_')
            return self.portrait_url(size)
        return self.__getattribute__(item)

allianceauth/permissions_tool/models.py
from django.db import models


class PermissionsTool(models.Model):
    """
    Dummy model for holding permissions
    """
    class Meta:
        managed = False
        permissions = (
            ('audit_permissions', 'Can audit permissions'),
        )

allianceauth/templates/allianceauth/base.html
{% load static %}
{% load i18n %}
{% load navactive %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    {% include 'allianceauth/icons.html' %}

    <title>{% block title %}{% block page_title %}{% endblock page_title %} - Alliance Auth{% endblock title %}</title>

    {% include 'bundles/bootstrap-css.html' %}
    {% include 'bundles/fontawesome.html' %}

    <link href="{% static 'css/auth-base.css' %}" type="text/css" rel="stylesheet">
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
{% if user.is_authenticated %}
    <div id="wrapper" class="container">
        <!-- Navigation -->
        {% include 'allianceauth/top-menu.html' %}
        <div class="row" id="site-body-wrapper">
            {% include 'allianceauth/side-menu.html' %}
            <div class="col-sm-10">
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <div class="alert alert-{{ message.level_tag }}">{{ message }}</div>
                        {% if not forloop.last %}
                            <br>
                        {% endif %}
                    {% endfor %}
                {% endif %}
                {% block content %}
                {% endblock content %}
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
{% endif %}
{% include 'bundles/bootstrap-js.html' %}
{% block extra_javascript %}
{% endblock extra_javascript %}
<script>
    {% block extra_script %}
    {% endblock extra_script %}
</script>
</body>
</html>

allianceauth/templates/allianceauth/help.html
{% extends "allianceauth/base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Help" %}{% endblock page_title %}

{% block content %}
    <div class="col-lg-12">

        <h1 class="page-header text-center">{%  trans "Help" %}</h1>

        <div class="container-fluid">
            <div class="embed-responsive embed-responsive-16by9">
                <iframe class="embed-responsive-item" src="https://allianceauth.readthedocs.io/en/latest/features/"></iframe>
            </div>
        </div>
    </div>
{% endblock content %}

allianceauth/templates/allianceauth/icons.html
{% load static %}
<link rel="icon" type="image/png" href="{% static 'icons/favicon-16x16.png' %}" sizes="16x16">
<link rel="icon" type="image/png" href="{% static 'icons/favicon-32x32.png' %}" sizes="32x32">
<link rel="icon" type="image/png" href="{% static 'icons/favicon-96x96.png' %}" sizes="96x96">
<link rel="apple-touch-icon" href="{% static 'icons/apple-touch-icon.png' %}">

allianceauth/templates/allianceauth/night-toggle.html
{% load i18n %}
<a href="{% url 'nightmode' %}?next={{ request.path|urlencode }}">
    {% trans "Night" %}
    <i class="fa {% if NIGHT_MODE %}fa-toggle-on{% else %}fa-toggle-off{% endif %}" aria-hidden="true"></i>
</a>

allianceauth/templates/allianceauth/side-menu.html
{% load i18n %}
{% load navactive %}
{% load menu_items %}
<div class="col-sm-2 auth-side-navbar" role="navigation">
    <div class="collapse navbar-collapse auth-menus-collapse auth-side-navbar-collapse">
        <ul class="nav nav-pills nav-stacked gray-icon-color" id="side-menu">
            <li>
                <a class="{% navactive request 'authentication:dashboard' %}"
                   href="{% url 'authentication:dashboard' %}">
                    <i class="fa fa-dashboard fa-fw"></i> {% trans "Dashboard" %}
                </a>
            </li>
            <li>
                <a class="{% navactive request 'groupmanagement:groups' %}" href="{% url 'groupmanagement:groups' %}">
                    <i class="fa fa-cogs fa-fw fa-sitemap"></i> {% trans "Groups" %}
                </a>
            </li>

            {% if can_manage_groups %}
                <li>
                    <a class="{% navactive request 'groupmanagement:management groupmanagement:membership groupmanagement:membership_list' %}"
                       href="{% url 'groupmanagement:management' %}">
                        <i class="fa fa-lock fa-sitemap fa-fw"></i> {% trans "Group Management" %}
                    </a>
                </li>
            {% endif %}

            {% menu_items %}

            <li>
                <a class="{% navactive request 'authentication:help' %}"
                   href="{% url 'authentication:help' %}">
                    <i class="fa fa-question fa-fw"></i> {% trans "Help" %}
                </a>
            </li>
        </ul>
    </div>
</div>

allianceauth/templates/allianceauth/top-menu.html
{% load i18n %}
{% load static %}
{% load navactive %}
<nav class="navbar navbar-default navbar-static-top auth-navbar-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".auth-menus-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand">
                <img src="{% static 'icons/favicon-32x32.png' %}" style="display: inline-block;" height="32" width="32"/>
                {{ SITE_NAME }}
            </a>
        </div>
        <div class="collapse navbar-collapse auth-menus-collapse">
            <ul class="nav navbar-nav navbar-right navbar-pills">
                    <li>
                        {% include 'allianceauth/night-toggle.html' %}
                    </li>
                {% if notifications %}
                    <li class="{% navactive request 'notifications:' %}">
                        <a href="{% url 'notifications:list' %}">Notifications
                            <span class="badge">{{ notifications }}</span>
                        </a>
                    </li>
                {% else %}
                    <li><a href="{% url 'notifications:list' %}">
                        <i class="fa fa-bell-o"></i></a>
                    </li>
                {% endif %}
                {% if user.is_authenticated %}
                    {% if user.is_staff %}
                        <li><a href="{% url 'admin:index' %}">{% trans "Admin" %}</a></li>
                    {% endif %}
                    <li><a href="{% url 'auth_logout' %}">{% trans "Logout" %}</a></li>
                {% else %}
                    <li><a href="{% url 'authentication:login' %}">{% trans "Login" %}</a></li>
                {% endif %}
            </ul>
            <form id="f-lang-select" class="navbar-form navbar-right" action="{% url 'set_language' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <select onchange="this.form.submit()" class="form-control" id="lang-select" name="language">
                        {% get_language_info_list for LANGUAGES as languages %}
                        {% for language in languages %}
                            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %}
                                    selected="selected"{% endif %}>
                                {{ language.name_local }} ({{ language.code }})
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </form>
        </div>
    </div>
</nav>