allianceauth/fleetup/urls.py
from django.conf.urls import url

from . import views

app_name = 'fleetup'

urlpatterns = [
    url(r'^$', views.fleetup_view, name='view'),
    url(r'^fittings/$', views.fleetup_fittings, name='fittings'),
    url(r'^fittings/(?P<fittingnumber>[0-9]+)/$', views.fleetup_fitting, name='fitting'),
    url(r'^doctrines/$', views.fleetup_doctrines, name='doctrines'),
    url(r'^characters/$', views.fleetup_characters, name='characters'),
    url(r'^doctrines/(?P<doctrinenumber>[0-9]+)/$', views.fleetup_doctrine, name='doctrine'),
]

allianceauth/hrapplications/urls.py
from django.conf.urls import url

from . import views

app_name = 'hrapplications'

urlpatterns = [
    url(r'^$', views.hr_application_management_view,
        name="index"),
    url(r'^create/$', views.hr_application_create_view,
        name="create_view"),
    url(r'^create/(\d+)', views.hr_application_create_view,
        name="create_view"),
    url(r'^remove/(\w+)', views.hr_application_remove,
        name="remove"),
    url(r'^view/(\w+)', views.hr_application_view,
        name="view"),
    url(r'^personal/view/(\w+)', views.hr_application_personal_view,
        name="personal_view"),
    url(r'^personal/removal/(\w+)',
        views.hr_application_personal_removal,
        name="personal_removal"),
    url(r'^approve/(\w+)', views.hr_application_approve,
        name="approve"),
    url(r'^reject/(\w+)', views.hr_application_reject,
        name="reject"),
    url(r'^search/', views.hr_application_search,
        name="search"),
    url(r'^mark_in_progress/(\w+)', views.hr_application_mark_in_progress,
        name="mark_in_progress"),
    ]

allianceauth/urls.py
import esi.urls

from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

import allianceauth.authentication.views
import allianceauth.authentication.urls
import allianceauth.notifications.urls
import allianceauth.groupmanagement.urls
import allianceauth.services.urls
from allianceauth.authentication.decorators import main_character_required, decorate_url_patterns
from allianceauth import NAME
from allianceauth import views
from allianceauth.authentication import hmac_urls
from allianceauth.hooks import get_hooks

admin.site.site_header = NAME


# Functional/Untranslated URL's
urlpatterns = [
    # Locale
    url(r'^i18n/', include('django.conf.urls.i18n')),

    # Authentication
    url(r'', include(allianceauth.authentication.urls)),
    url(r'^account/login/$', TemplateView.as_view(template_name='public/login.html'), name='auth_login_user'),
    url(r'^account/', include(hmac_urls)),

    # Admin urls
    url(r'^admin/', admin.site.urls),

    # SSO
    url(r'^sso/', include((esi.urls, 'esi'), namespace='esi')),
    url(r'^sso/login$', allianceauth.authentication.views.sso_login, name='auth_sso_login'),

    # Notifications
    url(r'', include(allianceauth.notifications.urls)),

    # Groups
    url(r'', include(allianceauth.groupmanagement.urls)),

    # Services
    url(r'', decorate_url_patterns(allianceauth.services.urls.urlpatterns, main_character_required)),

    # Night mode
    url(r'^night/', views.NightModeRedirectView.as_view(), name='nightmode')
]


# Append app urls
app_urls = get_hooks('url_hook')
for app in app_urls:
    urlpatterns += [url(r'', decorate_url_patterns([app().include_pattern], main_character_required))]

allianceauth/hrapplications/models.py
from django.contrib.auth.models import User
from django.db import models
from sortedm2m.fields import SortedManyToManyField

from allianceauth.eveonline.models import EveCharacter
from allianceauth.eveonline.models import EveCorporationInfo


class ApplicationQuestion(models.Model):
    title = models.CharField(max_length=254, verbose_name='Question')
    help_text = models.CharField(max_length=254, blank=True, null=True)
    multi_select = models.BooleanField(default=False)

    def __str__(self):
        return "Question: " + self.title


class ApplicationChoice(models.Model):
    question = models.ForeignKey(ApplicationQuestion,on_delete=models.CASCADE,related_name="choices")
    choice_text = models.CharField(max_length=200, verbose_name='Choice')

    def __str__(self):
        return self.choice_text

class ApplicationForm(models.Model):
    questions = SortedManyToManyField(ApplicationQuestion)
    corp = models.OneToOneField(EveCorporationInfo, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.corp)


class Application(models.Model):
    form = models.ForeignKey(ApplicationForm, on_delete=models.CASCADE, related_name='applications')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='applications')
    approved = models.NullBooleanField(blank=True, null=True, default=None)
    reviewer = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True)
    reviewer_character = models.ForeignKey(EveCharacter, on_delete=models.SET_NULL, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " Application To " + str(self.form)

    class Meta:
        permissions = (
            ('approve_application', 'Can approve applications'), ('reject_application', 'Can reject applications'),
            ('view_apis', 'Can view applicant APIs'),)
        unique_together = ('form', 'user')

    @property
    def main_character(self):
        return self.user.profile.main_character

    @property
    def characters(self):
        return [o.character for o in self.user.character_ownerships.all()]

    @property
    def reviewer_str(self):
        if self.reviewer_character:
            return str(self.reviewer_character)
        elif self.reviewer:
            return "User " + str(self.reviewer)
        else:
            return None


class ApplicationResponse(models.Model):
    question = models.ForeignKey(ApplicationQuestion, on_delete=models.CASCADE)
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='responses')
    answer = models.TextField()

    def __str__(self):
        return str(self.application) + " Answer To " + str(self.question)

    class Meta:
        unique_together = ('question', 'application')


class ApplicationComment(models.Model):
    application = models.ForeignKey(Application, on_delete=models.CASCADE, related_name='comments')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.user) + " comment on " + str(self.application)

allianceauth/hrapplications/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _


class HRApplicationCommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea, required=False, label=_("Comment"))


class HRApplicationSearchForm(forms.Form):
    search_string = forms.CharField(max_length=254, required=True, label=_("Search String"))

allianceauth/fleetup/views.py
import datetime
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.shortcuts import render
from django.template.defaulttags import register
from django.utils.translation import ugettext_lazy as _

from .managers import FleetUpManager

logger = logging.getLogger(__name__)


@register.filter
def get_item(dictionary, key):
    return dictionary.get(key)


@login_required
@permission_required('auth.view_fleetup')
def fleetup_view(request):
    logger.debug("fleetup_view called by user %s" % request.user)

    operations_list = FleetUpManager.get_fleetup_operations()
    if operations_list is None:
        messages.add_message(request, messages.ERROR, _("Failed to get operations list, contact your administrator"))
        operations_list = {}
    timers_list = FleetUpManager.get_fleetup_timers()
    if timers_list is None:
        messages.add_message(request, messages.ERROR, _("Failed to get timers list, contact your administrator"))
        timers_list = {}
    now = datetime.datetime.now().strftime('%H:%M:%S')

    context = {"timers_list": sorted(timers_list.items()),
               "operations_list": sorted(operations_list.items()),
               "now": now}

    return render(request, 'fleetup/index.html', context=context)


@login_required
@permission_required('auth.human_resources')
@permission_required('auth.view_fleetup')
def fleetup_characters(request):
    logger.debug("fleetup_characters called by user %s" % request.user)

    member_list = FleetUpManager.get_fleetup_members()
    if member_list is None:
        messages.add_message(request, messages.ERROR, _("Failed to get member list, contact your administrator"))
        member_list = {}

    context = {"member_list": sorted(member_list.items())}

    return render(request, 'fleetup/characters.html', context=context)


@login_required
@permission_required('auth.view_fleetup')
def fleetup_fittings(request):
    logger.debug("fleetup_fittings called by user %s" % request.user)
    fitting_list = FleetUpManager.get_fleetup_fittings()

    if fitting_list is None:
        messages.add_message(request, messages.ERROR, _("Failed to get fitting list, contact your administrator"))
        fitting_list = {}

    context = {"fitting_list": sorted(fitting_list.items())}
    return render(request, 'fleetup/fittingsview.html', context=context)


@login_required
@permission_required('auth.view_fleetup')
def fleetup_fitting(request, fittingnumber):
    logger.debug("fleetup_fitting called by user %s" % request.user)
    fitting_eft = FleetUpManager.get_fleetup_fitting_eft(fittingnumber)
    fitting_data = FleetUpManager.get_fleetup_fitting(fittingnumber)
    doctrinenumber = FleetUpManager.get_fleetup_doctrineid(fittingnumber)
    doctrines_list = FleetUpManager.get_fleetup_doctrine(doctrinenumber)

    if fitting_eft is None or fitting_data is None or doctrinenumber is None:
        messages.add_message(request, messages.ERROR, _("There was an error getting some of the data for this fitting. "
                                                        "Contact your administrator"))

    context = {"fitting_eft": fitting_eft,
               "fitting_data": fitting_data,
               "doctrines_list": doctrines_list}
    return render(request, 'fleetup/fitting.html', context=context)


@login_required
@permission_required('auth.view_fleetup')
def fleetup_doctrines(request):
    logger.debug("fleetup_doctrines called by user %s" % request.user)
    doctrines_list = FleetUpManager.get_fleetup_doctrines()
    if doctrines_list is None:
        messages.add_message(request, messages.ERROR, _("Failed to get doctrines list, contact your administrator"))

    context = {"doctrines_list": doctrines_list}
    return render(request, 'fleetup/doctrinesview.html', context=context)


@login_required
@permission_required('auth.view_fleetup')
def fleetup_doctrine(request, doctrinenumber):
    logger.debug("fleetup_doctrine called by user %s" % request.user)
    doctrine = FleetUpManager.get_fleetup_doctrine(doctrinenumber)
    if doctrine is None:
        messages.add_message(request, messages.ERROR, _("Failed to get doctine, contact your administrator"))
    context = {"doctrine": doctrine}
    return render(request, 'fleetup/doctrine.html', context=context)

stock/templates/registered/addsigniture.html
{% extends "public/base.html" %}
{% load bootstrap %}
{% load staticfiles %}

{% block title %}Alliance Auth - Signiture Create{% endblock %}

{% block page_title %}Create Signiture{% endblock page_title %}
{% block extra_css %}
    <link href="{% static 'css/jquery.datetimepicker.css' %}" rel="stylesheet" type="text/css">{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">Create Signiture</h1>

        <div class="container-fluid">
            <div class="col-md-4 col-md-offset-4">
                <div class="row">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">Create Signiture</button>
                        </form>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

{% block extra_script %}

    $('#id_eve_time').datetimepicker({
    maskInput: true,
    format: 'Y-m-d H:i',minDate:0
    });

{% endblock extra_script %}

stock/templates/registered/fleetupcharacters.html
{% extends "registered/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}
{% block page_title %}FleetUp{% endblock page_title %}

{% block content %}
<div class="col-lg-12">
{% if perms.auth.corp_stats %}
    <nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Fleet-Up</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'auth_fleetup_view' %}">{% trans "Ops and Timers" %}</a></li>
                <li><a href="{% url 'auth_fleetup_doctrines' %}">{% trans "Doctrines" %}</a></li>
                <li><a href="{% url 'auth_fleetup_fittings' %}">{% trans "Fittings" %}</a></li>
                
                <li class="active"><a href="{% url 'auth_fleetup_characters' %}">{% trans "Characters" %} <span class="sr-only">(current)</span></a></li>
                
                <li></li>
            </ul>
        </div>
    </div>
    </nav>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">{% trans "Characters registered on Fleet-Up.com" %}</h3>
        </div>
            <div class="panel-body">
                <div class="col-lg-6">
                    <div class="table-responsive">   
                    <table class="table table-condensed table-hover table-striped">
                        <tr>
                            <th class="col-md-1"></th>
                            <th class="col-md-1">{% trans "Character" %}</th>
                            <th class="col-md-1">{% trans "Corporation" %}</th>
                            <th class="col-md-1">Fleet-Up(id)</th>
                        </tr>
                        {% for char_name, user_id in member_list %}
                        <tr>
                            <td>
                                <img src="http://image.eveonline.com/Character/{{ user_id.char_id }}_32.jpg" class="img-circle">
                            </td>
                            <td>
                                <p>{{ user_id.char_name }}</p>
                            </td>
                            <td>
                                <p>{{ user_id.corporation }}</p>
                            </td>
                            <td>
                                <p>{{ user_id.user_id }}</p>
                            </td>
                        {% endfor %}
                    </table>
                    </div>
                </div>
            </div>
    </div>
{% endif %}
</div>
{% endblock content %}

stock/templates/registered/fleetupdoctrinesview.html
{% extends "registered/base.html" %}
{% load bootstrap %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Alliance Auth{% endblock %}
{% block page_title %}FleetUp{% endblock page_title %}

{% block content %}
<div class="col-lg-12">
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">{% trans "Toggle navigation" %}</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Fleet-Up</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'auth_fleetup_view' %}">{% trans "Ops and Timers" %}</a></li>
                <li class="active"><a href="{% url 'auth_fleetup_doctrines' %}">{% trans "Doctrines" %} <span class="sr-only">(current)</span></a></li>
                <li><a href="{% url 'auth_fleetup_fittings' %}">{% trans "Fittings" %}</a></li>
                {% if perms.auth.corp_stats %}
                <li><a href="{% url 'auth_fleetup_characters' %}">{% trans "Characters" %}</a></li>
                {% endif %}
                <li></li>
            </ul>
        </div>
    </div>
</nav>
    <div class="panel">
        {% if doctrines_list %}
        {% for a, j in doctrines_list.items %}
        {% regroup j|dictsort:"FolderName" by FolderName as folder_list %}
            {% for FolderName in folder_list %}
            <div class="col-lg-8">
            <div class="panel panel-default">
                        <div class="panel-heading">
                            <h3 class="panel-title"><b>{{ FolderName.grouper }}</b></h3>
                        </div>
                        <div class="panel-body">
                            <table class="table table-condensed table-hover table-striped">
                                <tr>
                                    <th class="col-lg-1"></th>
                                    <th class="col-lg-4">{% trans "Name" %}</th>
                                    <th class="col-lg-3">{% trans "Doctrine" %}</th>
                                    <th class="col-lg-4">{% trans "Last updated" %}</th>
                                    <!--<th class="col-lg-1">Owner</th>
                                    <th class="col-lg-2">Note</th>-->
                                </tr>
                                {% for item in FolderName.list %}
                
                                <tr>
                                    <td>
                                    <a href="{% url 'auth_fleetup_doctrine' item.DoctrineId %}"><img src="https://image.eveonline.com/InventoryType/{{ item.IconId }}_32.png"></a>
                                    </td> 
                                    <td>
                                    {{ item.Name }}
                                    </td>
                                    <td>
                                    <a href="{% url 'auth_fleetup_doctrine' item.DoctrineId %}" class="btn btn-info btn-sm">{{ item.FolderName }}</a>
                                    </td>
                                    <td>
                                    {{ item.LastUpdatedString }}
                                    </td>
                                </tr>
                                {% endfor %}
                            </table>
                        </div>
            </div>
            </div>
            {% endfor %}
    </div>
        {% endfor %}

        {% else %}
        <h3>{% trans "There seems to be no Doctrines in here at the moment!" %}</h3>
        {% endif %}
    </div>
</div>

{% endblock content %}

stock/templates/registered/hrapplicationcorpchoice.html
{% extends "registered/base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block title %}Choose a Corp{% endblock %}
{% block page_title %}{% trans "Choose a Corp" %}{% endblock page_title %}
{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "Choose a Corp" %}</h1>
        {% if choices %}
            <div class="panel panel-primary">
                <div class="panel-heading">{% trans "Available Corps" %}</div>
                <table class="table table-responsive">
                    {% for choice in choices %}
                        <tr>
                            <td class="text-center">
                                <a href="{% url 'auth_hrapplication_create_view' choice.0 %}" class="btn btn-primary" title="Apply">{{ choice.1 }}</a>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="alert alert-danger">{% trans "No corps are accepting applications at this time." %}</div>
        {% endif %}
    </div>
{% endblock content %}

stock/templates/registered/hrapplicationview.html
{% extends "registered/base.html" %}
{% load staticfiles %}
{% load bootstrap %}
{% load i18n %}
{% load eveonline_extras %}

{% block title %}Alliance Auth - {% trans "View Application" %}{% endblock %}
{% block page_title %}{% trans "View Application" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <h1 class="page-header text-center">{% trans "View Application" %}</h1>
        <div class="container-fluid">
            <div class="col-md-6 col-md-offset-3">
                <div class="row">
                    {% if app.approved %}
                        <div class="alert alert-success text-center">{% trans "Approved" %}</div>
                    {% elif app.approved == False %}
                        <div class="alert alert-danger text-center">{% trans "Denied" %}</div>
                    {% else %}
                        <div class="alert alert-warning text-center">{% trans "Pending" %}</div>
                    {% endif %}
                    {% if app.reviewer_str %}
                        <div class="alert alert-info text-center">{% trans "Reviewer:" %} {{ app.reviewer_str }}</div>
                    {% endif %}
                </div>
                <div class="row">
                    <div class="panel panel-info">
                        <div class="panel-heading">{% trans "Applicant" %}</div>
                        <table class="table">
                            <tr>
                                <th class="text-center">{% trans "User" %}</th>
                                <th class="text-center">{% trans "Main Character" %}</th>
                            </tr>
                            <tr>
                                <td class="text-center">{{ app.user }}</td>
                                <td class="text-center">{{ app.main_character }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="panel panel-info">
                        <div class="panel-heading">{% trans "Characters" %}</div>
                        <table class="table">
                            <tr>
                                <th class="text-center"></th>
                                <th class="text-center">{% trans "Name" %}</th>
                                <th class="text-center">{% trans "Corp" %}</th>
                                <th class="text-center">{% trans "Alliance" %}</th>
                            </tr>
                            {% for char in app.characters %}
                                <tr>
                                    <td class="text-center">
                                        <img class="ra-avatar img-responsive img-circle"
                                             src="https://image.eveonline.com/Character/{{ char.character_id }}_32.jpg">
                                    </td>
                                    <td class="text-center">{{ char.character_name }}</td>
                                    <td class="text-center">{{ char.corporation_name }}</td>
                                    <td class="text-center">{{ char.alliance_name }}</td>
                                </tr>
                            {% endfor %}
                        </table>
                    </div>
                </div>
                <div class="row">
                    {% for response in responses %}
                        <div class="panel panel-default">
                            <div class="panel-heading">{{ response.question.title }}</div>
                            <div class="alert">{{ response.answer|linebreaksbr }}</div>
                        </div>
                    {% endfor %}
                </div>
                {% if buttons %}
                    {% if perms.auth.human_resources %}
                        <div class="row">
                            <div class="panel panel-primary">
                                <div class="panel-heading">{% trans "Actions" %}</div>
                                <div class="panel-body text-center">
                                    {% if app.approved == None %}
                                        {% if app.reviewer == user %}
                                            {% if perms.hrapplications.approve_application %}
                                                <a href="{% url 'auth_hrapplication_approve' app.id %}"
                                                   class="btn btn-success">{% trans "Approve" %}</a>
                                            {% endif %}
                                            {% if perms.hrapplications.reject_application %}
                                                <a href="{% url 'auth_hrapplication_reject' app.id %}"
                                                   class="btn btn-danger">{% trans "Reject" %}</a>
                                            {% endif %}
                                            {% if perms.hrapplications.delete_application %}
                                                <a href="{% url 'auth_hrapplication_remove' app.id %}"
                                                   class="btn btn-danger">{% trans "Delete" %}</a>
                                            {% endif %}
                                        {% elif not app.reviewer %}
                                            <a href="{% url 'auth_hrapplication_mark_in_progress' app.id %}"
                                               class="btn btn-warning">{% trans "Mark in Progress" %}</a>
                                        {% endif %}
                                    {% endif %}
                                    {% if perms.hrapplications.add_applicationcomment %}
                                        <button type="button" class="btn btn-primary" data-toggle="modal"
                                                data-target="#myModal">{% trans "Comment" %}</button>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                        <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                            <div class="panel panel-default">
                                <div class="panel-heading" role="tab" id="headingThree">
                                    <h4 class="panel-title">
                                        <a class="collapsed" data-toggle="collapse" data-parent="#accordion"
                                           href="#collapseThree" aria-expanded="false"
                                           aria-controls="collapseThree">
                                            {% trans 'Comments' %} ({{ comments.count }})
                                        </a>
                                    </h4>
                                </div>
                                <div id="collapseThree" class="panel-collapse collapse" role="tabpanel"
                                     aria-labelledby="headingThree">
                                    <div class="panel-body">
                                        {% for comment in comments %}
                                            <div class="panel panel-default">
                                                <div class="panel-heading" role="tab" id="">
                                                    <div class="panel-title">
                                                        <div class="pull-right">{{ comment.created }}</div>
                                                        <div class="pull-left">{% if comment.user.profile.main_character %}{{ comment.user.profile.main_character }}{% else %}{{ comment.user }}{% endif %}</div>
                                                        <div class="clearfix"></div>
                                                    </div>
                                                </div>
                                                <div class="panel-body">{{ comment.text|linebreaks }}</div>
                                            </div>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endif %}
            </div>
        </div>
    </div>
    {% if perms.hrapplications.add_applicationcomment %}
        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
             aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">
                            <span aria-hidden="true">&times;</span><span class="sr-only">{% trans "Close" %}</span>
                        </button>
                        <h4 class="modal-title" id="myModalLabel">{% trans "Add Comment" %}</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-signin" role="form" action="" method="POST">
                            {% csrf_token %}
                            {{ comment_form|bootstrap }}
                            <br/>
                            <button class="btn btn-lg btn-primary btn-block" type="submit">{% trans "Add Comment" %}</button>
                        </form>
                    </div>
                    <div class="modal-footer"></div>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}